### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by joncodo** [broadsoftxtended/Product-Phone-for-Chrome#14]
Need documentation on how to build it and package it
Need documentation on dependencies
Need documentation on how to translate/add another language.
Need documentation on how to do basic branding/logo change

**Comment by joncodo** [comment]
Done for now but I'm sure we will continually update them as time goes on

**Comment by joncodo** [comment]
Overview - Why and How it works.
Configuration and Provisioning on BroadWorks UC-One
- Configuring BroadWorks for UC-One Phone for Chrome
- Provisioning Users for UC-One Phone for Chrome

**Comment by joncodo** [comment]
From Joe Baird:

i haven't read through everything, but do we have the BroadWorks dependancies, R20, the WRS version and patch level, device type, dms config, etc.?

**Comment by joncodo** [comment]
@remlap42 Can you write something up concerning this comment for the docs? "i haven't read through everything, but do we have the BroadWorks dependancies, R20, the WRS version and patch level, device type, dms config, etc.?"

**Comment by remlap42** [comment]
All of this is covered in the section on Configuring BroadWorks.  

https://github.com/BroadSoft-Xtended/Product-Phone-for-Chrome/blob/master/documentation/BroadWorksConfiguration.md
