### ISSUE TITLE
2 - If you accidentally hit the backspace key...it kicks you out to the login screen.

### ISSUE THREAD

**Issue by remlap42** [broadsoftxtended/Product-Phone-for-Chrome#25]
Backspace should probably not be so dramatic.  Actually, when I look closely at what its doing --it's backspacing through the browser history of the chrome app.  Not sure that makes sense in the context of a chrome app.   Probalby should ignore the backspace unless you are in an edit field?

**Comment by joncodo** [comment]
Done
