### ISSUE TITLE
Unlimited number of ports in DTAF?

### ISSUE THREAD

**Issue by tobiasehlert** [broadsoftxtended/Product-Phone-for-Chrome#56]
Then DTAF which should be uploaded is set to be unlimited lines. That should not be correct, since the config file does only contain SIP credentials for one account? It should get changed in my opinion. =)

If so, switch
`<numberOfPorts>
<unlimited>true</unlimited>
</numberOfPorts>`

to following
`<numberOfPorts>
<quantity>1</quantity>
</numberOfPorts>`

/ Tobias

**Comment by joncodo** [comment]
I think you are correct on this one as well. I don't see that setting in the project though. Can you point me to the file where you found this? 

`<numberOfPorts> <unlimited>true</unlimited> </numberOfPorts>`

**Comment by tobiasehlert** [comment]
@jodonnell-broadsoft, I have created a pull-request with the adjustment. Also doublechecked and the DTAF zip file was accepted by our R21.sp1 system :)
