### ISSUE TITLE
Client does not  try to authenticate on 401 Unauthorized answer from XSP

### ISSUE THREAD

**Issue by tobiasehlert** [broadsoftxtended/Product-Phone-for-Chrome#57]
Client not authenticating correctly against BroadWorks.

When logging in, the client makes an OPTIONS request against following URL
`http(s)://<XSP>/com.broadsoft.xsi-actions/v2.0/user/<USERID>/directories/Enterprise HTTP/1.1`

The response is a normal 401 Unauthorized answer, but the client does not try to challenge it.. it just returns "Invalid username, password or login url".
The request does contain:
`WWW-Authenticate: Basic realm="XtendedServicesInterface"`
`Server: BW HTTP Server`

If the request is made towards a XSPFQDN, the XSP does return an 302 Found, but the client does not try to follow that new path either.
`Location: http(s)://<XSP>/com.broadsoft.xsi-actions/v2.0/user/<USERID>/directories/Enterprise`

**Comment by joncodo** [comment]
Is this something you would like to submit a pull request for?

Some of these things are not 100% as we were a bit limited on time. We released this as an open source project so talented people like you could make changes :)

Thanks so much for the feedback :+1:

**Comment by tobiasehlert** [comment]
Closing issue.. not working with this software anymore.
